# Uncomment this line to define a global platform for your project
# platform :ios, '7.0'

target 'CoreDataTest' do

pod "AFNetworking", "~> 2.0"
pod "Reachability", "3.1.0"

end

target 'CoreDataTestTests' do

end

